querof\CodeBundle\Entity\Menu:
    type: entity
    table: menu
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        ord:
            type: integer
            nullable: false
            options:
                unsigned: false
        class:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
