querof\CodeBundle\Entity\Ticket:
    type: entity
    table: ticket
    indexes:
        IDX_97A0ADA39395C3F3:
            columns:
                - customer_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        date:
            type: date
            nullable: false
    manyToOne:
        customer:
            targetEntity: Customer
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                customer_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
