# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        arguments: [ '@request_stack' ]
        public: false
        tags:
            - { name: twig.extension }
    app.twig.controller_action_extension:
        class: AppBundle\Twig\ControllerActionExtension
        arguments: [ '@request_stack' ]
        tags:
            - { name: twig.extension }
    app.menu.menu_builder_extension:
        class: AppBundle\Twig\MenuBuilderExtension
        tags:
            - { name: twig.extension }
        arguments:
            em: "@doctrine.orm.entity_manager"
