menuoptions_index:
    path:     /
    defaults: { _controller: "querofCodeBundle:MenuOptions:index" }
    methods:  GET

menuoptions_show:
    path:     /{id}/show
    defaults: { _controller: "querofCodeBundle:MenuOptions:show" }
    methods:  GET

menuoptions_new:
    path:     /new
    defaults: { _controller: "querofCodeBundle:MenuOptions:new" }
    methods:  [GET, POST]

menuoptions_edit:
    path:     /{id}/edit
    defaults: { _controller: "querofCodeBundle:MenuOptions:edit" }
    methods:  [GET, POST]

menuoptions_delete:
    path:     /{id}/delete
    defaults: { _controller: "querofCodeBundle:MenuOptions:delete" }
    methods:  DELETE
